Updated all dependencies for KNIME 3.6 and 3.7
rdkit/knime-rdkit pull request #61
Opened 2019-05-11 21:59 UTC by manuelschwarze

Updated all MANIFEST.MF files to refer only to plugins available in KNIME
3.6 and 3.7 to ensure full compatibility.
Fixed internal RDKit plugins dependencies to be fully in sync with each
other.
Increased RDKit plugin / feature version to 3.6.1.
Updated feature copyrights to 2019.

2019-05-12 05:24 UTC, greglandrum requested changes
I'd change the way the copyright dates have been updated, but otherwise looks good.

2019-05-12 05:24 UTC, greglandrum commented on org.rdkit.knime.binaries.feature/feature.xml
> +      Copyright (C) 2019 Novartis Institutes for BioMedical Research
I think it's better to do this as: `Copyright (C) 2015-2019` in order to indicate the full timeline.

2019-05-12 07:14 UTC, manuelschwarze commented
Then it has to be 2012-2019

-Manuel

Sent from my iPhone

Am 12.05.2019 um 07:24 schrieb Greg Landrum <notifications@github.com<mailto:notifications@github.com>>:


@greglandrum requested changes on this pull request.

I'd change the way the copyright dates have been updated, but otherwise looks good.

________________________________

In org.rdkit.knime.binaries.feature/feature.xml<https://github.com/rdkit/knime-rdkit/pull/61#discussion_r283119930>:

>        provider-name="NIBR">

    <description>
       This feature contains RDKit binaries for use as dependencies for other packages.
    </description>

    <copyright>
-      Copyright (C) 2015 Novartis Institutes for BioMedical Research
+      Copyright (C) 2019 Novartis Institutes for BioMedical Research


I think it's better to do this as: Copyright (C) 2015-2019 in order to indicate the full timeline.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/rdkit/knime-rdkit/pull/61#pullrequestreview-236401778>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABPK4WLYNHAUKANBZWS5CWLPU6S2HANCNFSM4HMJCCLQ>.

2019-05-12 13:35 UTC, greglandrum commented
Ok; I was just going from what was there before. The usual thing with copyright dates (I think) is to just extend the second (later) date when a “significant” change is made

2019-05-13 15:15 UTC, manuelschwarze commented on org.rdkit.knime.binaries.feature/feature.xml
> +      Copyright (C) 2019 Novartis Institutes for BioMedical Research
Ok, I put now the initial year as first and the last change year as second.

2019-05-13 15:16 UTC, merged