Bump rdkit binaries to 2021.03.5
rdkit/knime-rdkit pull request #95
Opened 2021-09-16 11:31 UTC by greglandrum

I've updated to the most recent binaries on the 2021.03 release series. This is still a patch release relative to v2021.03.1, which is what we're currently distributing.

I also discovered an error in the way I had done the linux builds for the last binary release which could lead to crashes in some circumstances. I fixed that build flag when I did these new builds, so that's also cleared up.

I also tried to bump the version numbers of just the binaries and the binaries feature within the plugin itself, hopefully I got that right.

2021-09-23 07:30 UTC, manuelschwarze commented
@greglandrum , although only the binaries have changed, we always change also all other version numbers. There are mainly 2 reasons for it:

- Proper dependencies: We should ensure also by declaration, that the types and nodes (and all other extensions, e.g. wizard) have the proper dependency configured to the latest binaries. Changing the dependency to something so fundamental like the binaries is an important change, hence it also deserves a new version number. It is not only the the version definition itself (which you changed already in binaries), but also the version that we list as dependent version different files, which is important. 

- Convenience: Changing version numbers in so many different files is a pain and it is easy to miss something. When using the Eclipse File Search functionality and the integrated replacement functionality it is very easy to just target the correct version numbers X1.Y1.Z1 and change them to X2.Y2.Z2, if you know that X1.Y1.Z1 is used everywhere in our RDKit KNIME extensions.

Please try that Eclipse functionality to replace all version numbers from 4.3.0 to 4.3.1.

2021-09-23 07:50 UTC, manuelschwarze requested changes
As discussed

2021-09-23 10:38 UTC, manuelschwarze commented
Tested on Windows 10 with KNIME 4.3 successfully.
Test on Mac Catalina 10.5 crashed:
12:28:46.245] => Running Tests for Add Conformers/Add Conformers - Default Tests                                             ...WARN 	 Testflow executor (Tests for Add Conformers/Add Conformers - Default Tests) TestflowConfiguration	 No node with id '73' found in workflow, but we have a configuration for it. Ignoring the configuration.

`java.lang.IllegalArgumentException: No such node ID: 0:73
	at org.knime.core.node.workflow.WorkflowManager.getNodeContainer(WorkflowManager.java:6819)
	at org.knime.core.node.workflow.WorkflowManager.findNodeContainer(WorkflowManager.java:10005)
	at org.knime.testing.core.ng.TestflowConfiguration.load(TestflowConfiguration.java:208)
	at org.knime.testing.core.ng.TestflowConfiguration.<init>(TestflowConfiguration.java:143)
	at org.knime.testing.core.ng.WorkflowTestContext.setWorkflowManager(WorkflowTestContext.java:138)
	at org.knime.testing.core.ng.WorkflowLoadSaveLoadTest.run(WorkflowLoadSaveLoadTest.java:107)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)
	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:368)
	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:271)
	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:243)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:190)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN 	 Testflow executor (Tests for Add Conformers/Add Conformers - Default Tests) TestflowConfiguration	 No node with id '73' found in workflow, but we have a configuration for it. Ignoring the configuration.
java.lang.IllegalArgumentException: No such node ID: 0:73
	at org.knime.core.node.workflow.WorkflowManager.getNodeContainer(WorkflowManager.java:6819)
	at org.knime.core.node.workflow.WorkflowManager.findNodeContainer(WorkflowManager.java:10005)
	at org.knime.testing.core.ng.TestflowConfiguration.load(TestflowConfiguration.java:208)
	at org.knime.testing.core.ng.TestflowConfiguration.<init>(TestflowConfiguration.java:143)
	at org.knime.testing.core.ng.WorkflowTestContext.setWorkflowManager(WorkflowTestContext.java:138)
	at org.knime.testing.core.ng.WorkflowLoadSaveLoadTest.run(WorkflowLoadSaveLoadTest.java:119)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)
	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:368)
	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:271)
	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:243)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:190)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011a103c60, pid=26828, tid=0x0000000000013703
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libGraphMolWrap.jnilib+0x313c60]  _ZNKSt3__16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN11ForceFields3UFF12AtomicParamsEEENS_19__map_value_compareIS7_SB_NS_4lessIS7_EELb1EEENS5_ISB_EEE4findIS7_EENS_21__tree_const_iteratorISB_PNS_11__tree_nodeISB_PvEElEERKT_+0x50
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/KNIME SDK 4.2.app/Contents/MacOS/hs_err_pid26828.log
WARN 	 KNIME-Worker-5-RDKit Add Conformers 0:74 Node	 Node created an empty data table.
[thread 79107 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#`

[hs_err_pid26828.log](https://github.com/rdkit/knime-rdkit/files/7216849/hs_err_pid26828.log)

2021-09-23 11:27 UTC, greglandrum commented
> Tested on Windows 10 with KNIME 4.3 successfully.
> Test on Mac Catalina 10.5 crashed:
> 12:28:46.245] => Running Tests for Add Conformers/Add Conformers - Default Tests ...WARN Testflow executor (Tests for Add Conformers/Add Conformers - Default Tests) TestflowConfiguration No node with id '73' found in workflow, but we have a configuration for it. Ignoring the configuration.
> 
> ```
> java.lang.IllegalArgumentException: No such node ID: 0:73
> 	at org.knime.core.node.workflow.WorkflowManager.getNodeContainer(WorkflowManager.java:6819)
> 	at org.knime.core.node.workflow.WorkflowManager.findNodeContainer(WorkflowManager.java:10005)
> 	at org.knime.testing.core.ng.TestflowConfiguration.load(TestflowConfiguration.java:208)
> 	at org.knime.testing.core.ng.TestflowConfiguration.<init>(TestflowConfiguration.java:143)
> 	at org.knime.testing.core.ng.WorkflowTestContext.setWorkflowManager(WorkflowTestContext.java:138)
> 	at org.knime.testing.core.ng.WorkflowLoadSaveLoadTest.run(WorkflowLoadSaveLoadTest.java:107)
> 	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)
> 	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:368)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:271)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:243)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:190)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> WARN 	 Testflow executor (Tests for Add Conformers/Add Conformers - Default Tests) TestflowConfiguration	 No node with id '73' found in workflow, but we have a configuration for it. Ignoring the configuration.
> java.lang.IllegalArgumentException: No such node ID: 0:73
> 	at org.knime.core.node.workflow.WorkflowManager.getNodeContainer(WorkflowManager.java:6819)
> 	at org.knime.core.node.workflow.WorkflowManager.findNodeContainer(WorkflowManager.java:10005)
> 	at org.knime.testing.core.ng.TestflowConfiguration.load(TestflowConfiguration.java:208)
> 	at org.knime.testing.core.ng.TestflowConfiguration.<init>(TestflowConfiguration.java:143)
> 	at org.knime.testing.core.ng.WorkflowTestContext.setWorkflowManager(WorkflowTestContext.java:138)
> 	at org.knime.testing.core.ng.WorkflowLoadSaveLoadTest.run(WorkflowLoadSaveLoadTest.java:119)
> 	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:250)
> 	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:368)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:271)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:243)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:190)
> 	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x000000011a103c60, pid=26828, tid=0x0000000000013703
> #
> # JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
> # Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode bsd-amd64 compressed oops)
> # Problematic frame:
> # C  [libGraphMolWrap.jnilib+0x313c60]  _ZNKSt3__16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN11ForceFields3UFF12AtomicParamsEEENS_19__map_value_compareIS7_SB_NS_4lessIS7_EELb1EEENS5_ISB_EEE4findIS7_EENS_21__tree_const_iteratorISB_PNS_11__tree_nodeISB_PvEElEERKT_+0x50
> #
> # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> #
> # An error report file with more information is saved as:
> # /Applications/KNIME SDK 4.2.app/Contents/MacOS/hs_err_pid26828.log
> WARN 	 KNIME-Worker-5-RDKit Add Conformers 0:74 Node	 Node created an empty data table.
> [thread 79107 also had an error]
> #
> # If you would like to submit a bug report, please visit:
> #   https://github.com/AdoptOpenJDK/openjdk-support/issues
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> ```
> 
> [hs_err_pid26828.log](https://github.com/rdkit/knime-rdkit/files/7216849/hs_err_pid26828.log)

Do the tests pass without the updated binary?

2021-09-23 11:28 UTC, greglandrum commented
> @greglandrum , although only the binaries have changed, we always change also all other version numbers. There are mainly 2 reasons for it:
> 
> * Proper dependencies: We should ensure also by declaration, that the types and nodes (and all other extensions, e.g. wizard) have the proper dependency configured to the latest binaries. Changing the dependency to something so fundamental like the binaries is an important change, hence it also deserves a new version number. It is not only the the version definition itself (which you changed already in binaries), but also the version that we list as dependent version in different files, which is important.
> * Convenience: Changing version numbers in so many different files is a pain and it is easy to miss something. When using the Eclipse File Search functionality and the integrated replacement functionality it is very easy to just target the correct version numbers X1.Y1.Z1 and change them to X2.Y2.Z2, if you know that X1.Y1.Z1 is used everywhere in our RDKit KNIME extensions.
> 
> Please try that Eclipse functionality to replace all version numbers from 4.3.0 to 4.3.1.

I believe that the reason we switched to separate packages for the rdkit binaries and the nodes was to allow *exactly* the situation where one is updated and the other isn't. That's what we're doing here.

2021-09-23 11:59 UTC, manuelschwarze commented
> I believe that the reason we switched to separate packages for the rdkit binaries and the nodes was to allow _exactly_ the situation where one is updated and the other isn't. That's what we're doing here.

The reason why we have separate plugins for the binaries is how Eclipse loads and activates binaries based on OS and hardware architecture. Another reason was that the types plugin that includes the binary plugins is used also in other extensions. Versioning is really secondary here. But since many years I am watching closely that the versions are kept in sync to void mistakes. Let's keep it like that, please.

2021-09-23 12:09 UTC, greglandrum commented
> The reason why we have separate plugins for the binaries is how Eclipse loads and activates binaries based on OS and hardware architecture. Another reason was that the types plugin that includes the binary plugins is used also in other extensions. Versioning is really secondary here. But since many years I am watching closely that the versions are kept in sync to void mistakes. Let's keep it like that, please.

I disagree with this but want to get this fix out quickly so that KNIME users don't have to wait for us to argue

2021-09-23 12:18 UTC, greglandrum commented
@manuelschwarze : done

2021-09-23 14:25 UTC, manuelschwarze commented
> Do the tests pass without the updated binary?

I tested with the last version on Mac, and with that one it does not crash.

2021-09-23 14:46 UTC, greglandrum commented
> > Do the tests pass without the updated binary?
> 
> I tested with the last version on Mac, and with that one it does not crash.

The last release version or the current github master?

2021-09-23 15:30 UTC, manuelschwarze commented
> > > Do the tests pass without the updated binary?
> > 
> > 
> > I tested with the last version on Mac, and with that one it does not crash.
> 
> The last release version or the current github master, because we need to compare to the github master

I locally rolled back to the commit before your recent 2 commits in a local branch when I tested. I am currently in a training, if you need another testing round on Mac, needs to wait until tomorrow morning.

2021-09-23 16:44 UTC, manuelschwarze commented
> > > > Do the tests pass without the updated binary?
> > > 
> > > 
> > > I tested with the last version on Mac, and with that one it does not crash.
> > 
> > 
> > The last release version or the current github master, because we need to compare to the github master
> 
> I locally rolled back to the commit before your recent 2 commits in a local branch when I tested. I am currently in a training, if you need another testing round on Mac, needs to wait until tomorrow morning.

I just switched back to your dev/rdkit_2021_03_5 branch (and also got your latest version changes) and ran the Add Confirmer RDKit Test Workflows successfully with GUI - the same that were crashing earlier. Then I reran them fully without GUI, and also this time there was no crash. Pretty fuzzy. There is a chance that the first crash was caused by Eclipse, if for some reason it still had older RDKit wrapper classes in its file system cache. That's the only "good" explanation that comes to my mind. Or it is a raise condition that happens only once in a while. It was a funny long method name in which it crashed - is there anything non-thread safe it these algorithms behind that code?

2021-09-23 16:57 UTC, greglandrum commented
> 
> I just switched back to your dev/rdkit_2021_03_5 branch (and also got your latest version changes) and ran the Add Confirmer RDKit Test Workflows successfully with GUI - the same that were crashing earlier. Then I reran them fully without GUI, and also this time there was no crash. Pretty fuzzy. There is a chance that the first crash was caused by Eclipse, if for some reason it still had older RDKit wrapper classes in its file system cache. That's the only "good" explanation that comes to my mind. Or it is a raise condition that happens only once in a while. It was a funny long method name in which it crashed - is there anything non-thread safe it these algorithms behind that code?

No, that should all be thread safe. The underlying C++ is all tested multi-threaded and we don't hit problems with it. That, of course, doesn't mean it's perfect... thread safety is and remains non-trivial to get 100% right.

Still, it sounds like things seem to be working. Ok, to merge this PR now?

2021-09-23 22:38 UTC, manuelschwarze approved these changes
I also tested on Linux (CentOS7) with KNIME 4.3, and there all tests went through fine as well.
If we assume that the Mac crash was just a flaw caused by Eclipse file cache, then I would think that merging the PR should be fine.

2021-09-23 22:38 UTC, manuelschwarze commented on org.rdkit.knime.nodes/META-INF/MANIFEST.MF
> +Bundle-Version: 4.3.1.qualifier
Further down it says here:
org.rdkit.knime.types;bundle-version="[4.0.0,5.0.0)"
In my opinion this is dangerous, it must have slipped in the past. I think, we need to set that to [4.3.1,5.0.0) - always at least to the latest version that we tested our nodes with. And that change is exactly why I was pushing for a newer nodes version, because it changes what the nodes are doing. The binaries do not care about the nodes, and it makes sense to have them now as separate feature (e.g. for Vernalis), but our RDKit nodes, they do care about the binaries and would require one particular version. With the wide version range we open the door for strange installations and strange error reports.

2021-09-24 09:15 UTC, greglandrum commented on org.rdkit.knime.nodes/META-INF/MANIFEST.MF
> +Bundle-Version: 4.3.1.qualifier
OK. I will fix that in a separate

2021-09-24 09:15 UTC, merged